baseurl: "/"
title: Partido Migala
theme: 
languageCode: es-mx
copyright: Migala

params:
  mainSections:
    - post
  intro: false
  headline: Proyecto Migala
  description: UNA REVOLUCIÓN GLOBAL, ORGULLOSAMENTE MEXICANA. Más que un partido, somos una alianza de personas con ganas de cambiar al mundo. La política es sólo otra herramienta.
  opengraph: true
  logo: ./img/semilla.webp
  dateFormat: "2.1.2006"

permalinks:
  post: "/posts/:filename/"

menu:
  main:
    - name: Redes Sociales
      url: /page/redes-sociales
      weight: 1
    - name: Horizontalidad
      url: /page/horizontalidad
      weight: 4
    - name: Reglamento
      url: /page/reglamento
      weight: 8

site:
  author:
    - name: Kevin